import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Header, Highlight} from '../components/Header'
import React, { useState } from 'react';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>v2dawn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header styles={styles}/>
      <main className={styles.main}>
        <Highlight styles={styles} img_src="/images/God-of-War-Ragnarok-2.jpg"/>
      </main>
    </div>
  )
}
